name: Release
on:
  push:
    branches:
      - '**'

jobs:
  pr-release:
    runs-on: ubuntu-latest

    timeout-minutes: 5

    permissions:
      id-token: write
      contents: read
      pull-requests: write
      repository-projects: read

    steps:
      - name: Generate Token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.token }}
          ref: ${{ github.base_ref }}
          fetch-depth: 0
