name: Prod Apply

on:
  workflow_dispatch:
    branches:
      - main

jobs:
  prod-apply:
    name: Prod Apply
    runs-on: ubuntu-latest
    environment:
      name: prod
    steps:
      - run: echo "本番デプロイ"